Bring in some :cloud:.gov workflow stuff

diff --git a/rc/aliases b/rc/aliases
--- a/rc/aliases
+++ b/rc/aliases
@@ -75,9 +75,88 @@ alias delete_cisco_connect_profiles='pls rm -rvf /opt/cisco/anyconnect/profile/g
 
 # Concourse Fly
 #
-alias fr-jump-stage='fly -t fr trigger-job -j jumpbox/container-bosh-staging -w; fly -t fr intercept -j jumpbox/container-bosh-staging -s jumpbox'
-alias fr-jump-prod='fly -t fr trigger-job -j jumpbox/container-bosh-production -w; fly -t fr intercept -j jumpbox/container-bosh-production -s jumpbox'
-alias fr-jump-tooling='fly -t fr trigger-job -j jumpbox/container-bosh-tooling -w; fly -t fr intercept -j jumpbox/container-bosh-tooling -s jumpbox'
-alias fr-jump-dev='fly -t fr trigger-job -j jumpbox/container-bosh-development -w; fly -t fr intercept -j jumpbox/container-bosh-development -s jumpbox'
+getConcourseJumpbox() {
+  local environment=$1
+  local match="^(staging|development|tooling|production)$"
+  if [[ -z $ci_env ]]
+  then
+    echo "Environmental variable \$ci_env isn't set, so defaulting to `fr`"
+    ci_env=fr
+  fi
+  if ! [[ $environment =~ $match ]]
+  then
+    echo "Please pass in a supported environment ( e.g. development, tooling, staging, production )"
+    return
+  fi
+  echo "Creating a Jumpbox in ${environment}"
+  trigger=$(fly -t ${ci_env} trigger-job -w -j jumpbox/container-bosh-${environment})
+  build=$(echo ${trigger} | head -n 1 | awk '{print $3}' | sed 's/.*#\([0-9]\{1,\}\)/\1/')
+  echo "Jumpbox ${environment} #${build}"
+
+  sleep 1
+  fly -t ${ci_env} intercept -j jumpbox/container-bosh-${environment} -b ${build} -s jumpbox
+}
+
+alias fly-jumpbox=getConcourseJumpbox
 
 export shh=~/Developer/cloud.gov/secrets
+
+getConcourseCreds() {
+  local root_dir=$1
+  local config="${root_dir}pipeline.yml"
+  local creds="${root_dir}credentials.yml"
+
+  $shh/download-credentials.sh "${creds}" && \
+  fly -t fr sp -p "$(echo "${PWD##*/}" | sed 's/cg-//')" -c "${config}" -l "${creds}";
+  vim "${creds}" && \
+  fly -t fr sp -p "$(echo "${PWD##*/}" | sed 's/cg-//')" -c "${config}" -l "${creds}" && \
+  $shh/upload-credentials.sh "${creds}"
+}
+
+alias fly-creds=getConcourseCreds
+
+# UAA
+#
+authUaaEnvironment() {
+  local target_index=$1
+
+  if [ $target_index -eq 0 ]
+  then
+    secret=$(
+      aws --profile fr s3 cp s3://cloud-gov-varz-stage/cf-staging.main.yml - | \
+      openssl enc -aes-256-cbc -d -a -pass "pass:$(fly -t fr gp -p deploy-cf | spruce json | jq -r '.resources | map(select(.name == "common-staging")) | .[].source.secrets_passphrase')" | \
+      sed '/\( merge \)/d' | \
+      spruce json | \
+      jq -r .properties.uaa.admin.client_secret
+    )
+  elif [ $target_index -eq 1 ]
+  then
+    secret=$(
+      aws --profile fr s3 cp s3://cloud-gov-varz/cf.main.yml - | \
+      openssl enc -aes-256-cbc -d -a -pass "pass:$(fly -t fr gp -p deploy-cf-new | spruce json | jq -r '.resources | map(select(.name == "common-production")) | .[].source.secrets_passphrase')" | \
+      sed '/\( merge \)/d' | \
+      spruce json | \
+      jq -r .properties.uaa.admin.client_secret
+    )
+  elif [ $target_index -eq 4 ]
+  then
+    secret=$(
+      aws --profile fr s3 cp s3://cloud-gov-varz/tooling-bosh.yml - | \
+      openssl enc -aes-256-cbc -d -a -pass "pass:$(fly -t fr gp -p deploy-bosh | spruce json | jq -r '.resources | map(select(.name == "common-tooling")) | .[].source.secrets_passphrase')" | \
+      sed '/\( merge \)/d' | \
+      spruce json | \
+      jq -r .properties.uaa.admin.client_secret
+    )
+  fi
+
+  if [[ $target_index == 0 || $target_index == 1 || $target_index == 4 ]]
+  then
+    uaac target "${target_index}"
+    uaac token client get admin -s ${secret}
+  else
+    echo "You can't target a UAA I don't know about. Please run \`uaac targets\` and modify this shell function."
+  fi
+}
+
+alias uaac-get=authUaaEnvironment
+
